-- MySQL Script generated by MySQL Workbench
-- Wed Apr 18 15:12:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_sisaps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sisaps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sisaps` DEFAULT CHARACTER SET utf8 ;
USE `db_sisaps` ;

-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_regiao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_regiao` (
  `id_regiao` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `regiao` VARCHAR(80) NULL,
  PRIMARY KEY (`id_regiao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_bibliografia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_bibliografia` (
  `id_bibliografia` INT NOT NULL AUTO_INCREMENT,
  `fonte` VARCHAR(255) NULL,
  `autor` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_bibliografia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_parte_planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_parte_planta` (
  `id_parte_planta` INT NOT NULL AUTO_INCREMENT,
  `parte_planta` VARCHAR(255) NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_parte_planta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NOT NULL,
  `observacao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(255) NOT NULL,
  `email_user` VARCHAR(255) NOT NULL,
  `cpf_user` VARCHAR(13) NOT NULL,
  `telefone_user` VARCHAR(15) NULL,
  `celular_user` VARCHAR(15) NULL,
  `cep` VARCHAR(45) NULL,
  `cidade` VARCHAR(80) NULL,
  `logadouro` VARCHAR(80) NULL,
  `num_casa` VARCHAR(9) NULL,
  `id_perfil` INT NOT NULL,
  `primeiro_login` TINYINT(1) NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_tb_perfil_tb1_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_user_tb_perfil_tb1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `db_sisaps`.`tb_perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_plantas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_plantas` (
  `id_plantas` INT NOT NULL AUTO_INCREMENT,
  `nome_cientifico` VARCHAR(60) NOT NULL,
  `nome_popular` VARCHAR(60) NOT NULL,
  `modo_preparo` VARCHAR(255) NULL,
  `foto_planta` LONGBLOB NULL,
  `cuidados` VARCHAR(255) NOT NULL,
  `efeitos_colaterais` VARCHAR(255) NOT NULL,
  `principio_efeitos` VARCHAR(255) NOT NULL,
  `tb_regiao_id_regiao` INT NOT NULL,
  `id_bibliografia` INT NOT NULL,
  `id_parte_planta` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_plantas`),
  INDEX `fk_tb_plantas_tb_regiao1_idx` (`tb_regiao_id_regiao` ASC),
  INDEX `fk_tb_plantas_tb_bibliografia1_idx` (`id_bibliografia` ASC),
  INDEX `fk_tb_plantas_tb_parte_planta1_idx` (`id_parte_planta` ASC),
  INDEX `fk_tb_plantas_tb_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_tb_plantas_tb_regiao1`
    FOREIGN KEY (`tb_regiao_id_regiao`)
    REFERENCES `db_sisaps`.`tb_regiao` (`id_regiao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plantas_tb_bibliografia1`
    FOREIGN KEY (`id_bibliografia`)
    REFERENCES `db_sisaps`.`tb_bibliografia` (`id_bibliografia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plantas_tb_parte_planta1`
    FOREIGN KEY (`id_parte_planta`)
    REFERENCES `db_sisaps`.`tb_parte_planta` (`id_parte_planta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_plantas_tb_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_sisaps`.`tb_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_parte_corpo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_parte_corpo` (
  `id_parte_corpo` INT NOT NULL AUTO_INCREMENT,
  `parte_corpo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_parte_corpo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_sintomas` (
  `id_sintomas` INT NOT NULL AUTO_INCREMENT,
  `nome_cientifico` VARCHAR(60) NOT NULL,
  `nome_popular` VARCHAR(60) NOT NULL,
  `causas` VARCHAR(255) NULL,
  `tratamentos` VARCHAR(255) NULL,
  `id_parte_corpo` INT NOT NULL,
  PRIMARY KEY (`id_sintomas`),
  INDEX `fk_tb_sintomas_tb_parte_corpo1_idx` (`id_parte_corpo` ASC),
  CONSTRAINT `fk_tb_sintomas_tb_parte_corpo1`
    FOREIGN KEY (`id_parte_corpo`)
    REFERENCES `db_sisaps`.`tb_parte_corpo` (`id_parte_corpo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`planta_sintoma_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`planta_sintoma_tb` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL,
  `sintomas_id_sintomas` INT NOT NULL,
  PRIMARY KEY (`id`, `sintomas_id_sintomas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sisaps`.`tb_plantas_sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sisaps`.`tb_plantas_sintomas` (
  `id_planta_sintomas` INT NOT NULL AUTO_INCREMENT,
  `id_plantas` INT NOT NULL,
  `id_sintomas` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_planta_sintomas`, `id_plantas`, `id_sintomas`),
  INDEX `fk_plantas_tb_has_sintomas_tb_sintomas_tb1_idx` (`id_sintomas` ASC),
  INDEX `fk_plantas_tb_has_sintomas_tb_plantas_tb1_idx` (`id_plantas` ASC),
  CONSTRAINT `fk_plantas_tb_has_sintomas_tb_plantas_tb1`
    FOREIGN KEY (`id_plantas`)
    REFERENCES `db_sisaps`.`tb_plantas` (`id_plantas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plantas_tb_has_sintomas_tb_sintomas_tb1`
    FOREIGN KEY (`id_sintomas`)
    REFERENCES `db_sisaps`.`tb_sintomas` (`id_sintomas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
